model:
  model_name_or_path: denial07/Qwen2-72B-Instruct-kor-dpo # models/bllossom_aug/checkpoint-1400 # Bllossom/llama-3.2-Korean-Bllossom-3B
  load_in_8b: True

data:
  train_csv: data/combined_cleaned_org.csv
  inference_csv: data/test.csv
  output_csv: outputs/qwen_denial.csv
  train_test_split_ratio: 0.1
  tokenize_max_length: 1700

train:
  do_train: True
  do_eval: True
  lr_scheduler_type: cosine
  max_seq_length: 1700
  output_dir: models/qwen_denial
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  max_steps: 800
  learning_rate: 5e-5
  weight_decay: 0.01
  logging_steps: 20
  save_strategy: steps
  eval_strategy: steps
  eval_steps: 100
  save_steps: 100
  save_total_limit: 5
  save_only_model: True
  fp16: True
  warmup_steps: 500
  report_to: none

seed: 42

peft:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ['q_proj', 'k_proj']
  bias: none
  task_type: CAUSAL_LM

prompt:
  PROMPT_NO_QUESTION_PLUS: |
    지문:
    {paragraph}

    질문:
    {question}

    선택지:
    {choices}

    1, 2, 3, 4, 5 중에 하나를 정답으로 고르세요.
    정답:
    
  PROMPT_QUESTION_PLUS: |
    지문:
    {paragraph}

    질문:
    {question}

    <보기>:
    {question_plus}

    선택지:
    {choices}

    1, 2, 3, 4, 5 중에 하나를 정답으로 고르세요.
    정답:
  
  tokenizer_chat_template: "{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\' }}{% endif %}{% if message['role'] == 'system' %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% elif message['role'] == 'user' %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n' + '<|im_start|>' + 'assistant' + '\n' }}{% elif message['role'] == 'assistant' %}{{message['content'] + '<|im_end|>'}}{% endfor %}"
  
  response_template: "<|im_start|>assistant\n"
  
  # evaluation.py의 compute_metrics에서 정답 분리할 때 쓰는 compute_metrics_split
  compute_metrics_end_token: "<|im_end|>"

  system_message: "당신은 지문을 읽고 객관식 문제의 정답을 찾는 AI 어시스턴트입니다. 지문을 분석한 뒤, 선택지 번호(1, 2, 3, 4, 5) 중 하나만 반환하세요. 추가 설명은 작성하지 마세요."
